### ISSUE TITLE
UZT documentation

### ISSUE THREAD

**Issue by vivekbedekar** [MODFLOW-USGS/mt3d-usgs#35]
From: Feinstein, Daniel [mailto:dtfeinst@usgs.gov] 
Sent: Sunday, May 6, 2018 2:34 PM
To: Vivek Bedekar <vivekb@sspa.com>
Subject: ahh- the problem I think is with MT3D-USGS documentation

Hi Vivek,

Referring to my last email:

The I/O manual for UZT it seems to say that you need to make INCUZET=-1 and INCGWET=-1 even if no ET is active in UZF package. But that is not right.  The "-1" values act to make UZT reuse the infiltration concentration from the last stress period - which is disastrous for my run.

When I take out the previous INCUZET and INCGWET lines:
-1
-1
then the results make sense.

Is this the correct interpretation of the manual?  Maybe you have already addressed this problem in a
release?

I am sending you a new UZT package - please check the end to make sure it now
makes sense.

thanks much,
d

**Comment by emorway-usgs** [comment]
There is a comment in the code near where this happens:
```
C--If the check on IUZFBND called IUZFBND_CHK remains false,     
C--then the value of IUZFOPT can be set equal to zero, since all 
C--cells are effectively acting as though IUZFOPT=0
```
So, even though the user may specify that the IET starts out as one, if values read in the linker file state otherwise, the flag is reset.  

The clarification in the documentation looks good
