### ISSUE TITLE
Reverse the order of these pointer statements

### ISSUE THREAD

**Issue by langevin-usgs** [MODFLOW-USGS/mt3d-usgs#40]
https://github.com/MODFLOW-USGS/mt3d-usgs/blob/855359884a33ba715506225633e8a97462973975/src/fmi1mf6.f#L382

I think these should be the other way around

```
KPERMF6=>KPER, KSTPMF6=>KSTP
```

**Comment by emorway-usgs** [comment]
Fixed with 76d6fbb.  Thanks @langevin-usgs
