### ISSUE TITLE
Fix constant conc. boundary

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/mt3d-usgs#41]
The code originally introduced in commit 141f400 negates the constant concentration boundary condition.  

```C
C--RESET ICBUND TO ABS(ICBUND) FOR CONSTANT CONCENTRATION CELLS
      DO INDEX=1,NCOMP
        DO KK=1,NLAY
          DO II=1,NROW
            DO JJ=1,NCOL
              IF(ICBUND(JJ,II,KK,INDEX).LT.0) THEN
                ICBUND(JJ,II,KK,INDEX)=ABS(ICBUND(JJ,II,KK,INDEX))
              ENDIF
            ENDDO
          ENDDO
        ENDDO
      ENDDO  
```
None of our tests used this boundary condition and so it went undetected until now.  In trying to determine why this code was added, did it have something to do with transport through dry cells that can happen with the use of MF-NWT?

**Comment by langevin-usgs** [comment]
Attached is an mt3d example that demonstrates the problem.  
[p1mt3d.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/2715079/p1mt3d.zip)

**Comment by vivekbedekar** [comment]
Moved the loop into the right place, within an IF statement.
