### ISSUE TITLE
Error Reading SFR data from FTL file

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#56]
Mt3D-USGS encounters an error when reading SFR data from an unformated ftl file. The error occurs in the following lines of READPS.
C--MARK CELLS NEAR THE SINK/SOURCE
          IF(QSTEMP.LT.0 .AND. ICBUND(J,I,K).GT.0) THEN
            ICBUND(J,I,K)=1000+IQ
          ELSEIF(ICBUND(J,I,K).GT.0 ) THEN
            ICBUND(J,I,K)=1020+IQ
          ENDIF
The error occurs because when reading SFR data, there are two real values to be read for each cell but only one of them is actually read. For example, here is the beginning of the relevant portions of the ftl file when it is saved as a formatted file.
 SFR                       36
           1           1           1   1.028048       4500.000    
           1           2           2   2.706948       7000.000

**Comment by emorway-usgs** [comment]
@rbwinst-usgs would you mind posting the test models (MF & MT3D) that reproduces this error to this issue report?
