### ISSUE TITLE
LKT CINITLAK documentation issue

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#59]
If there is more than one solute in the simulation, how should CINITLAK be read? Should each line list the concentrations of each solute in the lake or should all the concentrations for the first solute be specified before the concentrations of the second solute?

**Comment by rbwinst-usgs** [comment]
Maybe just giving the dimensions of CINITLAK would clear this up

**Comment by rbwinst-usgs** [comment]
From the source code, it looks like RARRAY is called once for each solute but this isn't clear (to me) from the input instructions.

**Comment by vivekbedekar** [comment]
Thanks for catching this Richard. Added a note before CINITLAK stating "(Enter item 2 for each species)". I hope that clarifies the confusion.

**Comment by vivekbedekar** [comment]
Richard, if you think this is good, could you please close this issue? Otherwise, let me know if there is more clarification needed.
