### ISSUE TITLE
Does FTL have the correct SFR node number for diversions?

### ISSUE THREAD

**Issue by vivekbedekar** [MODFLOW-USGS/mt3d-usgs#62]
In the problem I am debugging, SFR file mentions that a diversion exists from segment 8 to segment 54. Segment 8 has 20 reaches. However, in the FTL file, the diversion is written to SFR node that represents segment 8, reach 1 (the first reach of segment 20). Should it be SFR node that represents segment 8, reach 20 (last reach)?

**Comment by emorway-usgs** [comment]
Using a smaller test problem, it would appear that this is in fact a bug, the diversion appears to be happening at the front end of a segment when it should be diverting from the end of a segment.  

![div](https://user-images.githubusercontent.com/3236576/57659021-af1cfc00-7595-11e9-8161-5e1d8e439f6b.PNG)

**Comment by vivekbedekar** [comment]
The error seems to be in the reported SFR node number in the FTL file.  Mass balance for the last reach suggests that diversion is being taken out of the last reach, however, the node to node reporting in FTL is likely reporting the first reach number instead of the last reach number.

**Comment by emorway-usgs** [comment]
A confirmation of the fix from Rich:

"A diversion (iseg=3) pulls water from the outflow of the last reach of the IUPSEG segment (iseg=2). This is done using the variable SGOTFLW, which is the flow out of the last reach of the IUPSEG segment (iseg=2)."

[Issue #34](https://github.com/rniswon/mfnwt/issues/34) on the MFNWT repo documents/links to the actual fix, which required an adjustment to LMT8 and not MT3D-USGS.  Next release of NWT should resolve this issue.
