### ISSUE TITLE
MF6 linker values: QYY

### ISSUE THREAD

**Issue by emorway-usgs** [MODFLOW-USGS/mt3d-usgs#63]
@langevin-usgs... in need of a little MF6 insight...

In working up one of the MF5/MF6 test problems - a 2D steady state model that is 31 rows x 46 columns with a single well located in cell 16,16 - results are showing a surprisingly large concentration discrepancy (2%) at the cell containing the well. In digging further, noticed that the QY values have the opposite sign using the MF6-generated output relative to the MF5-generated linker file.  A fairly easy problem to fix, but before multiplying the QY field by -1, wanted to make sure this change would fit with your expectations of what's contained in the MF6 cbc file?  

If you go [here](https://github.com/MODFLOW-USGS/mt3d-usgs/blob/FMI2/src/fmi1mf6.f) and look at lines 479-481, it would appear that all values in the MF6 cbc file are reversed from MF5 derivatives?

**Comment by langevin-usgs** [comment]
It does not seem right that you would multiply QY by -1.  In those lines of code FLOWJA is positive for flow into cell N.  If we look at the cell to the right, (N+1), then FLOWJA is positive to the left, which is why we flip the sign.  But for the flow front face, a positive FLOWJA means flow to the north from cell M (J, I+1, K) into cell N (J, I, K), so we don't have to flip the sign.

**Comment by emorway-usgs** [comment]
A few notes about the `FLOWJA()` vector read by the MF6 FMI routines:

- All 6 faces of a cell have a value for each node N, so values will be duplicated
- The recorded Q in` FLOWJA()` is always positive into the cell, regardless of whether that flow occurs on left, right, front, back, top, or bottom face.  

So, for flow on the front face, a positive value indicates into the cell (or from the cell to the south into the current cell), but from an LMT point-of-view, this is a negative flow direction.  In other words, LMT would only write a positive value if flow were from the current cell to the cell bordering its southern edge.  Thus, to get the signs right, we need to switch the sign for this face in `FLOWJA()`
