### ISSUE TITLE
UZT input file unit number is incorrectly specified.

### ISSUE THREAD

**Issue by RichardWinston** [MODFLOW-USGS/mt3d-usgs#66]
The UZT package is assigned a unit number of 24 but in in UZT1RP an attempt is made to read the UZT input from unit 7 instead of unit 24.
[InUZT_Bad.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/3387855/InUZT_Bad.zip)

**Comment by emorway-usgs** [comment]
@RichardWinston Thanks for posting this bug.  Should be working now.  We weren't setting the input file's unit number properly in the UZT1AR() routine.
