### ISSUE TITLE
Incorrect CTS unit number in documentation

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#76]
The input instructions for MT3D-USGS says that the default unit number for the CTS package is 6. However, in the source code it is set to 20.

**Comment by emorway-usgs** [comment]
As of commit [500989f](https://github.com/MODFLOW-USGS/mt3d-usgs/tree/500989fd830c470fd9634ec5c190470927be99fe), line 187 of [this file](https://github.com/MODFLOW-USGS/mt3d-usgs/blob/500989fd830c470fd9634ec5c190470927be99fe/src/mt3d-usgs.f) confirms that the unit number is indeed 20
