### ISSUE TITLE
MT3D-USGS crashes with the attached model.

### ISSUE THREAD

**Issue by rbwinst-usgs** [MODFLOW-USGS/mt3d-usgs#79]
MT3D-USGS crashes on line 822 of ssm1.f.
[Mt3dUsgsBug.zip](https://github.com/MODFLOW-USGS/mt3d-usgs/files/4838901/Mt3dUsgsBug.zip)

**Comment by vivekbedekar** [comment]
I tried running the sample problem you sent on my machine and it worked. I can, however, see why the line you mentioned might fail with another compiler.

We could replace:
      IF(FRCH.AND.FMIFMT6) GOTO 32
with
      IF(FMIFMT6) GOTO 32

FRCH is checked on the previous line so checking again doesn't make a difference.

Vivek


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by emorway-usgs** [comment]
Why don't we go ahead and make that change.  Do you want to make the change and submit as a PR @rbwinst-usgs? Or would you like us to do it and send you a new exe?

**Comment by rbwinst-usgs** [comment]
When I looked at the source, I don't see a line with "IF(FRCH.AND.FMIFMT6) GOTO 32".

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
rbwinst@usgs.gov<mailto:rbwinst@usgs.gov>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/


"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________

**Comment by vivekbedekar** [comment]
Eric - May be this got fixed somewhere along the way because the latest source code works.

Richard - Are you looking at the latest code on GitHub or the source of the last released version?

Vivek


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by rbwinst-usgs** [comment]
I looked at the source code of the last released version.

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
rbwinst@usgs.gov<mailto:rbwinst@usgs.gov>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/


"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.

________________________________

**Comment by vivekbedekar** [comment]
Thanks, Richard!

Eric - the new line in the latest code is taking care of the issue Richard noticed.

Vivek


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by emorway-usgs** [comment]
Do you have all that you need, @rbwinst-usgs?  I can send along a new exe until we are able to get the next release out, if that would be helpful to you?

**Comment by rbwinst-usgs** [comment]
Please send the exe.

Richard B. Winston
US Geological Survey
Integrated Modeling and Prediction Division
rbwinst@usgs.gov<mailto:rbwinst@usgs.gov>
https://profile.usgs.gov/rbwinst<http://water.usgs.gov/nrp/gwsoftware/>
703-648-5988
on Wednesdays: 301 474-2762
Fax: 703 648-5274

The following are excellent guides especially for beginning modelers.
Reilly, T.E., 2001, System and boundary conceptualization in ground-water flow simulation:  U.S. Geological Survey Techniques of Water-Resources Investigations, book 3, chap. B8, 30 p.
https://water.usgs.gov/pubs/twri/twri-3_B8/<http://water.usgs.gov/pubs/twri/twri-3_B8/>

Reilly, T.E., and Harbaugh, A.W., 2004 , Guidelines for evaluating ground-water flow models: U.S. Geological Survey Scientific Investigations Report 2004-5038, 30 p.
https://pubs.usgs.gov/sir/2004/5038/


"Codes only live if somebody loves them." Matt Tonkin, June 2, 2015, MODFLOW and More 2015 Conference Panel Discussion.

"When you started to have that problem, when you couldn't get a solution, you could get help with that. You could not get any help if you had a conceptual screw-up in your understanding of the regional hydrology. If you didn't have a rough idea of what the evapotranspiration was, of what the big streams were doing, and how the stream flow was related to groundwater, there's where you could get into trouble where nobody else could help you." Gordon Bennett in an interview, Feb. 21, 2019.


________________________________

**Comment by emorway-usgs** [comment]
This issue was fixed previously and will be included in the next release.
