### ISSUE TITLE
MT3D-USGS input instructions show NROW/NCOL for some arrays

### ISSUE THREAD

**Issue by hankaiwen** [MODFLOW-USGS/mt3d-usgs#83]
My docs seem to show UZF defining IUZFBND column-wise: IUZFBND(NCOL,NROW) while UZT input instructions seem to use row-wise arrays: IUZFBND(NROW,NCOL). Typo in document - should be reversed?? Cheers, Kevin

**Comment by emorway-usgs** [comment]
thanks @hankaiwen, the document has been fixed on the repo and will go out with the next release of MT3D-USGS
