### ISSUE TITLE
Crash as soon as MODFLOWSTYLEARRAYS is added

### ISSUE THREAD

**Issue by hankaiwen** [MODFLOW-USGS/mt3d-usgs#84]
C:\GW_Models_LOCAL\TC_GW_Model_192_MT3DUSGS_v3>mt3d-usgs_1.1.0_64.exe TC_GW_Model_192.nam

 MT3D-USGS - Modular 3D Multi-Species Transport Model [Ver 1.1.0]
 and based on MT3DMS. MT3D-USGS developed in cooperation by
 S.S. Papadopulos & Associates and the U.S. Geological Survey

 Using NAME File: TC_GW_Model_192.nam
forrtl: severe (29): file not found, unit 100, file C:\GW_Models_LOCAL\TC_GW_Model_192_MT3DUSGS_v3\fort.100
Image              PC                Routine            Line        Source
mt3d-usgs_1.1.0_6  00007FF61559B41D  Unknown               Unknown  Unknown
mt3d-usgs_1.1.0_6  00007FF61554177A  Unknown               Unknown  Unknown
mt3d-usgs_1.1.0_6  00007FF61550965A  U2DREL                   1616  utl1.f
mt3d-usgs_1.1.0_6  00007FF6153BCEBC  BTN1AR                    585  btn1.f
mt3d-usgs_1.1.0_6  00007FF6154659D8  MAIN__                    171  mt3d-usgs.f
mt3d-usgs_1.1.0_6  00007FF6155FAD9E  Unknown               Unknown  Unknown
mt3d-usgs_1.1.0_6  00007FF6155FB199  Unknown               Unknown  Unknown
KERNEL32.DLL       00007FF805B46FD4  Unknown               Unknown  Unknown
ntdll.dll          00007FF807A5CEC1  Unknown               Unknown  Unknown

C:\GW_Models_LOCAL\TC_GW_Model_192_MT3DUSGS_v3>

**Comment by emorway-usgs** [comment]
@hankaiwen After activating the `MODFLOWStyleArrays` options, you'll have to systematically go through the model input files and change the header lines that precede array input.  Currently, your header lines are using `100` which is described in the MT3DMS manual.  For `MODFLOWStyleArrays`, you'll instead want to use something analogous to what's in the MODFLOW input.  So, perhaps something like:

`internal   1.0000 (10e14.6)                   -1`

**Comment by hankaiwen** [comment]
Thanks Eric!
